include:
  - services.compose.yaml

services:
  build-server:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
    volumes:
      - app_volume:/app

  # Caddy server configuration
  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - build-server
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - app_volume:/app
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
  app_volume:


networks:
  backend:
    driver: bridge
