# @TODO: move api and web builds into a single dockerfile

include:
  - services.compose.yaml

services:
  build-api:
    build:
      dockerfile: ./API.Dockerfile
    container_name: flowx_api
    environment:
      NODE_ENV: development
      MONGO_USER: $MONGO_USER
      MONGO_PASSWORD: $MONGO_PASSWORD
      MONGO_DATABASE_NAME: $MONGO_DATABASE_NAME
      MONGO_HOST: $MONGO_HOST
      MONGO_PORT: $MONGO_PORT
      API_PORT: $API_PORT
      API_HOST: $API_HOST
    ports:
      - 3000
    # networks:
    #   - backend
    network_mode: host
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    env_file:
      - .env

  build-web:
    build:
      dockerfile: ./WEB.Dockerfile
    container_name: flowx_web
    volumes:
      - app_volume:/app

  # Caddy server configuration
  caddy:
    image: caddy:latest
    restart: unless-stopped
    depends_on:
      - build-web
    ports:
      - '80:80'
      - '443:443'
      - '443:443/udp'
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - app_volume:/app
      - caddy_data:/data
      - caddy_config:/config

volumes:
  app_volume:
  caddy_data:
  caddy_config:


networks:
  backend:
    driver: bridge
  # host:
