# @TODO: Add redis password

services:
  # Redis configuration
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_space:/data
    networks:
      - backend
    env_file:
      - .env

  # Mongo configuration
  mongo:
    image: mongo:7
    restart: always
    ports:
      - '${MONGO_PORT}:27017'
    volumes:
      - mongo_space:/data/db
    networks:
      - backend
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    env_file:
      - .env

  # Mongo-express configuration
  mongo-express:
    image: mongo-express:latest
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    networks:
      - backend
    environment:
      # @FIXME: change credentials
      ME_CONFIG_MONGODB_URL: mongodb://${MONGO_USERNAME}:${MONGO_PASSWORD}@mongo:27017
      ME_CONFIG_MONGODB_AUTH_USERNAME: ${MONGO_WEB_USERNAME}
      ME_CONFIG_MONGODB_AUTH_PASSWORD: ${MONGO_WEB_PASSWORD}
    env_file:
      - .env

volumes:
  redis_space:
  mongo_space:

networks:
  backend:
    driver: bridge
