# @TODO: Add redis password

services:
  # Redis configuration
  redis:
    image: redis:alpine
    container_name: redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
    volumes:
      - redis_space:/data
    networks:
      - backend
    restart: always
    env_file:
      - .env

volumes:
  redis_space:

networks:
  backend:
    driver: bridge
