
[package]
authors = ['Davd0x37']
edition = '2021'
name = 'wasm-crypto'
version = '0.1.0'

[lib]
crate-type = [
  'cdylib',
  'rlib',
]

[feature]
default = [
  'console_error_panic_hook',
]

[dependencies]
argon2 = '0.5'
chacha20poly1305 = '0.10.1'
console_error_panic_hook = {version = "0.1.7", optional = true}
getrandom = {version = '0.2', features = ['js']}
hex = '0.4.3'
js-sys = '0.3'
rand_core = {version = '0.6', features = ['std']}
wasm-bindgen = '0.2'
web-sys = {version = '0.3', features = [
  'Window',
]}

[dev-dependencies]
wasm-bindgen-test = '0.3'

[profile.release]
lto = true
opt-level = 's'
