[package]
authors = ["Davd0x37"]
edition = "2021"
name = "crypto_flerovium"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[features]
default = ["console_error_panic_hook"]
# default = ["console_error_panic_hook", "wee_alloc"]

[dependencies]
argon2 = "0.4"
chacha20poly1305 = "0.10.1"
getrandom = {version = "0.2", features = ["js"]}
hex = "0.4.3"
rand_core = {version = "0.6", features = ["std"]}
wasm-bindgen = "0.2.78"
console_error_panic_hook = {version = "0.1.6", optional = true}
# wee_alloc = {version = "0.4.5", optional = true}

[dev-dependencies]
wasm-bindgen-test = "0.3.28"

[profile.release]
opt-level = "s"
lto = true
