"""
User schema
"""
type User {
  id: ID! # User ID
  name: String! # User name
  email: String! # User email - used to login
  password: String! # User password
  createdAt: DateTime! # Date of creation
  updatedAt: DateTime! # Date of last update
}

extend type Query {
  users: [User]! # Return all users
  user(id: ID!): User # Return a user by ID
}
